import { useEffect } from "react";

import { useUi } from "../data/store";
import type { SiteJson } from "../types/site";
import { AccessPoints } from "./AccessPoints";
import { FloorSlabs } from "./FloorSlabs";
import { UncertaintyEllipsoids } from "./UncertaintyEllipsoids";
import type { PositionEstimateWire } from "../types/wire";

/**
 * Loads the site fixture and renders the building.
 *
 * The fixture is generated by tools/export_fixtures.py from the same domain models the
 * API will serialise, and CI regenerates it and fails on any diff — so this path cannot
 * drift from the real one. It also remains permanently useful as the offline PWA demo
 * and the deterministic test golden.
 */
export function SiteScene() {
  const site = useUi((s) => s.site);
  const setSite = useUi((s) => s.setSite);

  useEffect(() => {
    let cancelled = false;
    fetch("/fixtures/site.json")
      .then((r) => {
        if (!r.ok) throw new Error(`site fixture: HTTP ${r.status}`);
        return r.json() as Promise<SiteJson>;
      })
      .then((data) => {
        if (!cancelled) setSite(data);
      })
      .catch((err) => {
        // Loud, not swallowed. A blank scene with a silent console is the failure mode
        // that costs an afternoon.
        console.error("[spectra] failed to load site fixture:", err);
      });
    return () => {
      cancelled = true;
    };
  }, [setSite]);

  if (!site) return null;

  // For demonstration: M2 uncertainty volume (1-sigma ellipse)
  const mockEstimates: PositionEstimateWire[] = [
    {
      tenant_id: "t-0",
      target_id: "demo-target",
      site_id: site.site_id,
      estimated_at: new Date().toISOString(),
      kind: "point",
      x: 10.0,
      y: 12.0,
      covariance_xy: [[8.0, -3.0], [-3.0, 5.0]],
      floor_id: site.floors[0]?.id ?? null,
      floor_confidence: 1.0,
      zone_id: null,
      zone_confidence: 0.0,
      downgrade_reason: null,
    },
  ];

  return (
    <group>
      <FloorSlabs site={site} />
      <AccessPoints site={site} />
      <UncertaintyEllipsoids site={site} estimates={mockEstimates} />
    </group>
  );
}
