"""Spatially correlated log-normal shadowing.

The usual shortcut is to add independent Gaussian noise to every RSSI sample. That is
wrong in a way that flatters the solver badly: independent noise averages out, so a
stationary target's position estimate converges to the truth if you just wait. Real
shadowing does not behave like that. It is a property of *where you are standing* -- a
body, a filing cabinet or a lift shaft between you and the AP produces a stable bias that
persists as long as you stay put, and decorrelates only as you move.

Modelling it as a smooth random field per AP means a stationary target gets a consistently
wrong reading, which is exactly the condition that exposes an over-confident filter.

The field is generated by deterministic hashing rather than a stored grid, so it is
reproducible from a seed, unbounded in extent, and needs no allocation.
"""

from __future__ import annotations

import hashlib
import math
import struct
from dataclasses import dataclass


def _unit_normal(*key: object) -> float:
    """A deterministic standard normal drawn from an arbitrary key.

    Uses blake2b for reproducibility across processes and platforms -- Python's built-in
    hash() is randomised per interpreter run and would make the simulator irreproducible.
    """
    digest = hashlib.blake2b(repr(key).encode(), digest_size=16).digest()
    a, b = struct.unpack("<QQ", digest)
    # Box-Muller, guarding against log(0).
    u1 = (a / 2**64) or 1e-12
    u2 = b / 2**64
    return math.sqrt(-2.0 * math.log(u1)) * math.cos(2.0 * math.pi * u2)


def _smoothstep(t: float) -> float:
    return t * t * (3.0 - 2.0 * t)


@dataclass(frozen=True, slots=True)
class ShadowingField:
    """Smooth Gaussian-ish field, one independent realisation per observer.

    `correlation_length_m` is the distance over which the shadowing decorrelates. Around
    5 m is a reasonable indoor figure: walk past a partition and the obstruction changes,
    but a step to the left does not.
    """

    seed: int = 0
    sigma_db: float = 3.0
    correlation_length_m: float = 5.0

    def __post_init__(self) -> None:
        if self.correlation_length_m <= 0:
            raise ValueError("correlation_length_m must be positive")
        if self.sigma_db < 0:
            raise ValueError("sigma_db cannot be negative")

    def value(self, observer_id: str, x: float, y: float, floor_level: int = 0) -> float:
        """Shadowing offset in dB at a point, for one observer."""
        if self.sigma_db == 0.0:
            return 0.0
        gx, gy = x / self.correlation_length_m, y / self.correlation_length_m
        x0, y0 = math.floor(gx), math.floor(gy)
        fx, fy = _smoothstep(gx - x0), _smoothstep(gy - y0)

        def corner(i: int, j: int) -> float:
            return _unit_normal(self.seed, observer_id, floor_level, i, j)

        top = corner(x0, y0) * (1 - fx) + corner(x0 + 1, y0) * fx
        bottom = corner(x0, y0 + 1) * (1 - fx) + corner(x0 + 1, y0 + 1) * fx
        # Bilinear blending of unit normals shrinks the variance; rescale so the field
        # actually has the requested sigma rather than a quietly smaller one.
        blended = top * (1 - fy) + bottom * fy
        weight = math.sqrt(((1 - fx) ** 2 + fx**2) * ((1 - fy) ** 2 + fy**2))
        return self.sigma_db * blended / weight
